apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
  spec:
    capacity:
      storage: 10Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
      gcePersistentDisk:
        pdName: conf-disk
        fsType: ext4
